name: Swift Package CI

on:
  push:
    branches:
      - development 
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: macos-latest # You can choose the runner platform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Swift Package
      run: swift build

    - name: Run Tests
      run: |
        if ! swift test; then
          echo "Tests failed"
          exit 1
        fi

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: |
        swiftlint --config ./.swiftlint.yml

    - name: Upload Test Results
      if: ${{ always() }} # Upload test results regardless of the test outcome
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .build/x86_64-apple-macosx/debug/*/test-results.xml